#!/bin/bash

mkdir -p '/'
cat << EOF | base64 -d > '/foo'
YmFy
EOF
chmod '0600' '/foo'



cat << EOF | base64 -d > '/etc/systemd/system/docker.service'
dW5pdA==
EOF

mkdir -p '/etc/systemd/system/docker.service.d'
cat << EOF | base64 -d > '/etc/systemd/system/docker.service.d/10-docker-opts.conf'
b3ZlcnJpZGU=
EOF

grep -sq "^nfsd$" /etc/modules || echo "nfsd" >>/etc/modules
modprobe nfsd
nslookup $(hostname) || systemctl restart systemd-networkd
systemctl daemon-reload

if grep -q '^GARDENLINUX_BUILD_ID=27.[01]' /etc/os-release && ! dpkg -V cifs-utils xfsprogs &>/dev/null
then
    PARTITION=$(mount -v | grep "^/.*/usr" | awk '{print $1}')
    mount -o remount,rw ${PARTITION} /usr
    until apt update -qq && apt install --no-upgrade -qqy cifs-utils xfsprogs
    do
        sleep 1
    done
    mount -o remount,ro ${PARTITION} /usr
fi
if grep -q '^GARDENLINUX_BUILD_ID=27.[01]' /etc/os-release
then
    mkdir -p /etc/docker
    cat << EOF > /etc/docker/daemon.json
{ "storage-driver": "overlay2",
  "default-ulimits": {
      "memlock": {
          "name": "memlock",
          "hard": 67108864,
          "soft": 67108864
      }
  }
}
EOF
fi
systemctl enable docker && systemctl restart docker
systemctl enable 'docker.service' && systemctl restart 'docker.service'
