#!/bin/bash

mkdir -p '/'
cat << EOF | base64 -d > '/foo'
YmFy
EOF
chmod '0600' '/foo'



cat << EOF | base64 -d > '/etc/systemd/system/docker.service'
dW5pdA==
EOF

mkdir -p '/etc/systemd/system/docker.service.d'
cat << EOF | base64 -d > '/etc/systemd/system/docker.service.d/10-docker-opts.conf'
b3ZlcnJpZGU=
EOF

grep -sq "^nfsd$" /etc/modules || echo "nfsd" >>/etc/modules
modprobe nfsd
nslookup $(hostname) || systemctl restart systemd-networkd
systemctl daemon-reload
systemctl enable docker && systemctl restart docker
systemctl enable 'docker.service' && systemctl restart 'docker.service'
