apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gardener-extension-os-gardenlinux
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gardener-extension-os-gardenlinux
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gardener-extension-os-gardenlinux
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- if semverCompare ">= 1.26-0" .Capabilities.KubeVersion.Version }}
  unhealthyPodEvictionPolicy: AlwaysAllow
{{- end }}
