apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: os-gardenlinux
  annotations:
    security.gardener.cloud/pod-security-enforce: baseline
spec:
  resources:
  - kind: OperatingSystemConfig
    type: gardenlinux
  - kind: OperatingSystemConfig
    type: memoryone-gardenlinux
