//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatingSystemConfiguration) DeepCopyInto(out *OperatingSystemConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.MemoryTopology != nil {
		in, out := &in.MemoryTopology, &out.MemoryTopology
		*out = new(string)
		**out = **in
	}
	if in.SystemMemory != nil {
		in, out := &in.SystemMemory, &out.SystemMemory
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatingSystemConfiguration.
func (in *OperatingSystemConfiguration) DeepCopy() *OperatingSystemConfiguration {
	if in == nil {
		return nil
	}
	out := new(OperatingSystemConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OperatingSystemConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
